common: &default_settings

  license_key: '4e1752d76b896584b362b30d4c8acf1f75a9bbb7'

  agent_enabled: true
  app_name: careprice_docker
  high_security: false

  enable_auto_app_naming: false
  enable_auto_transaction_naming: true

  log_level: info
  audit_mode: false
  log_file_count: 1
  log_limit_in_kbytes: 0
  log_daily: false
  log_file_name: newrelic_agent.log

  ssl: true

  max_stack_trace_lines: 30

  attributes:

    enabled: true

  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    log_sql: false
    stack_trace_threshold: 0.5
    explain_enabled: true
    explain_threshold: 0.5
    top_n: 20
  error_collector:
    enabled: true

    ignore_errors: akka.actor.ActorKilledException
    ignore_status_codes: 404

  analytics_events:

    enabled: true

    max_samples_stored: 2000

  cross_application_tracer:

    enabled: true

  thread_profiler:

    enabled: true

  browser_monitoring:

    auto_instrument: true


production:
  <<: *default_settings
  app_name: careprice
