version: '2'

services:
  careprices:
    build: docker
    ports:
      - "9200:9200"
    depends_on:
      - redis
      - mongo
      - mysql
  redis:
      image: redis
      ports:
        - "6379:6379"
  mongo:
    image: mongo:3.1
    ports:
      - "27017:27017"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=careprices
      - MYSQL_PASSWORD=careprices
      - MYSQL_DATABASE=careprices
