version: '2'

services:
  careprices:
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=careprices
      - MYSQL_PASSWORD=careprices
      - MYSQL_DATABASE=careprices
